### ISSUE TITLE
PropertiesMustHavePrivateSettersConventionSpecification FailureMessage is incorrect

### ISSUE THREAD

**Issue by slewis74** [andrewabest/Conventional#22]
Message incorrectly states that the properties must be protected, rather than private.

**Comment by andrewabest** [comment]
Fixed in https://github.com/andrewabest/Conventional/commit/3b77406ca7faf00e1b0d5304e692197d86c947d1

Just wait for the build to trickle through - https://ci.appveyor.com/project/andrewabest/conventional
