### ISSUE TITLE
Add convention for ensuring enums are identical

### ISSUE THREAD

**Issue by xwipeoutx** [andrewabest/Conventional#26]
I want to be able to assert that 2 enums are identical in both values and names, so that a `(TargetEnum)(int)sourceEnumValue` safely works within an `IQueryable.Select`

**Comment by xwipeoutx** [comment]
For completeness, here's a terribly implementation.  I'll probably fork/pull request/write tests when I get some time.

    public class HaveCorrespondingEnumSpecification : ConventionSpecification
    {
        private readonly Type[] _sourceTypes;

        public HaveCorrespondingEnumSpecification(IEnumerable<Type> sourceTypes)
        {
            _sourceTypes = sourceTypes.ToArray();
        }

        public HaveCorrespondingEnumSpecification(params Type[] sourceTypes)
        {
            _sourceTypes = sourceTypes;
        }

        public override ConventionResult IsSatisfiedBy(Type type)
        {
            var sourceType = _sourceTypes.FirstOrDefault(t => t.IsEnum && t.Name == type.Name);
            if (sourceType == null)
                return ConventionResult.NotSatisfied(type.Name, "does not match any of the supplied type names");

            var subjectValueNames = ToValueNameDictionary(type);
            var sourceValueNames = ToValueNameDictionary(sourceType);

            ConventionResult result = ConventionResult.Satisfied(type.Name);
            result = CompareEnums(subjectValueNames, sourceValueNames, result);
            result = CompareEnums(sourceValueNames, subjectValueNames, result);

            return result;
        }

        private static ConventionResult CompareEnums(Dictionary<int, string> left, Dictionary<int, string> right, ConventionResult result)
        {
            foreach (var leftValue in left)
            {
                if (!right.ContainsKey(leftValue.Key))
                    result = result.And(ConventionResult.NotSatisfied(leftValue.Value, $"{leftValue.Value} ({leftValue.Key}) does not match any values"));

                else if (right[leftValue.Key] != leftValue.Value)
                    result = result.And(ConventionResult.NotSatisfied(leftValue.Value, $"{leftValue.Value} ({leftValue.Key}) does not match names with the corresponding value"));
            }
            return result;
        }

        private static Dictionary<int, string> ToValueNameDictionary(Type type)
        {
            return Enum.GetValues(type).Cast<object>().ToDictionary(
                v => (int)v,
                v => Enum.GetName(type, v)
                );
        }

        protected override string FailureMessage => "Must have a corresponding type";
    }

**Comment by xwipeoutx** [comment]
And an example


            var dtoEnums = DtoAssembly
                .GetTypes().Where(t => t.IsEnum)
                .ToArray();

            var domainEnums = DomainAssembly
                .GetTypes().Where(t => t.IsEnum)
                .ToArray();

            dtoEnums
                .MustConformTo(new HaveCorrespondingEnumSpecification(domainEnums));

**Comment by andrewabest** [comment]
Sorry about the slow reply @xwipeoutx 

Looks like a great convention! More than happy to take a PR if you get the time at some point :+1:

**Comment by andrewabest** [comment]
Fixed with https://github.com/andrewabest/Conventional/pull/30

**Comment by xwipeoutx** [comment]
Oh, thanks for fixing my issue. Sorry about my complete lack of communication around this. Glad it's in :)
