### ISSUE TITLE
Removing .NET 4.0 Support

### ISSUE THREAD

**Issue by andrewabest** [andrewabest/Conventional#34]
I'm looking to introduce .NET core support.

In doing so, to avoid the big headache of multi-targeted code, I'd like to move away from .NET 4.0, and only support .NET 4.5+.

This will also clean up Conventional's codebase quite a bit, and make contributing to it easier, as I could merge the .Net 4.5 projects back into the core projects, and not need to link files all over the place.

Throwing this out to see if anyone has any objections to this? 

This would bump Conventional into 2.x. Anyone still requiring .NET 4.0 support could still use 1.x.

**Comment by KodrAus** [comment]
Seems like a good move to me, support for .NET 4 in the form of old releases should do the trick. Are you anticipating any major issues that might need to be backported or something?

**Comment by michaelnoonan** [comment]
I think it's a good idea. Every library that's ported to .NET Core is adding momentum in a positive direction (my opinion). Also I feel that because this is a test library, and you're bumping major version, there's less risk of pushing someone into an awkward situation.

**Comment by nootn** [comment]
Onwards and upwards!  I think if you leave a Nuget version around that is .NET 4.0 compatible no one can really complain (I.e. your 1.X version), and any new features only end up in the new one.

**Comment by todthomson** [comment]
:shipit:

**Comment by andrewabest** [comment]
@KodrAus no big issues backporting that I could see, just didn't want to tick anyone off by doing it 'out of the blue'.

Looks like an overwhelming :+1: - so this shall be happening soon(ish)!

**Comment by andrewabest** [comment]
Will leave this open for a while longer to see if anyone else has a contrary opinion.

**Comment by andrewabest** [comment]
Half a year later... a status update!

It has been quite painful attempting to convert to netstandard - in particular the Reflection libraries only seem to be advanced enough in netstandard 1.5, and I suspect most people avoid 1.5 and 1.6 as odd anachronisms, and will be holding out for netstandard 2.

Current thinking is I'll await netstandard 2 dropping in Q3 2017, which will also give Cecil time to reach 1.0 with core support.

Closing this off for the moment, will reopen an issue with .NET Core support detailing plans separately.
