### ISSUE TITLE
Track releases in Github and add NuGet badge to README.md

### ISSUE THREAD

**Issue by dennisroche** [andrewabest/Conventional#57]
In AppVeyor you can configure the deployment to push to both NuGet and GitHub. It is useful to be able to track what commit for a version and the changes included. 

Then add a https://shields.io/ badge for the NuGet package.

**Comment by dennisroche** [comment]
It looks like it has worked. 👍

**Comment by andrewabest** [comment]
It seems that adding the deployment to github has added some unwanted behaviour to the build, will re-open this until I sort it out.

**Comment by dennisroche** [comment]
Does the GitHub release trigger another `master` change? So, it went from `4.0.2`  with the README.md to `4.0.3` with no code change?

You need to turn off build on `tag` pushes

**Comment by andrewabest** [comment]
Yup just figured out it was the `4.0.2` tag that triggered a `4.0.3` build. I've fixed it, closing this out again.
