### ISSUE TITLE
Scan a sql server database for tables without a clustered index

### ISSUE THREAD

**Issue by bendetat** [andrewabest/Conventional#7]
because sql azure will bork on a db migration that creates a table without a clustered index. Making ben sad.

**Comment by andrewabest** [comment]
An interesting suggestion - do you propose scanning the scripts that end up comprising a database, or you actually want to connect to and enforce conventions against a SQL instance?

**Comment by bendetat** [comment]
I reckon against the database itself. Once the precedent is set it would be fairly easy to extend this to other database-y conventions too.

**Comment by andrewabest** [comment]
I'm working on something for this, should have a PR up for discourse by EOW.

**Comment by bendetat** [comment]
:sweet_potato:

**Comment by andrewabest** [comment]
https://github.com/andrewabest/Conventional/pull/8 :shipit:

**Comment by andrewabest** [comment]
:steam_locomotive: choo choo, there goes the release train!

**Comment by bendetat** [comment]
![](https://38.media.tumblr.com/tumblr_m9n0cuG4vV1rcam23o1_500.gif)
