### ISSUE TITLE
Dlls from transient / SDKs specification should disallow subdirectories under dotnet/packs

### ISSUE THREAD

**Issue by flakey-bit** [andrewabest/Conventional#70]
Wondering if the convention `MustNotReferenceDllsFromTransientOrSdkDirectoriesConventionSpecification` should include files under `dotnet/packs` (`c:\Program Files\dotnet\packs`) in its checking.

In fact, possibly all of 

- `dotnet/shared`
- `dotnet/sdk`

should be verboten too?

**Comment by flakey-bit** [comment]
@andrewabest If you agree with the proposal, happy to send through a PR.

**Comment by andrewabest** [comment]
I agree with it in principal - just reading through https://docs.microsoft.com/en-us/dotnet/core/build/distribution-packaging and want to ensure excluding that shared directory is OK.

**Comment by flakey-bit** [comment]
I actually don't know **for sure** - struggling to find documentation confirming one way or the other. 

https://github.com/dotnet/designs/pull/50

![image](https://user-images.githubusercontent.com/4413825/73015943-de546e80-3e81-11ea-9e78-1846d552514b.png)

Feel free to close this issue I guess - or leave it open until we know.

**Comment by andrewabest** [comment]
@flakey-bit I think the best course of action here given the complexity is to wait until this bites someone and they need a convention around it (the classic case for writing conventions) :) Closing until then.
